backend:
  name: github
  repo: omegasenior/omegasenior.github.io # Path to your Github repository
  branch: master # Branch to update (master by default)
  publish_mode: editorial_workflow
  

media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, e.g., /admin/collections/:slug/edit
